apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    application: eap-app
    template: eap72-basic-s2i
    xpaas: 1.2.0
  - apiVersion: build.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:triggers: {}
      f:status:
        f:lastVersion: {}
    manager: openshift-apiserver
    operation: Update
  name: eap-app
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: eap-app:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/sqtran/hello-world-war.git
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: MAVEN_MIRROR_URL
      - name: MAVEN_ARGS_APPEND
        value: -Dcom.redhat.xpaas.repo.jbossorg
      - name: ARTIFACT_DIR
      forcePull: true
      from:
        kind: ImageStreamTag
        name: jboss-eap72-openshift:1.2
        namespace: openshift
      incremental: true
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: RcutDEtI
    type: GitHub
  - generic:
      secret: dc4KgoQo
    type: Generic
  - imageChange:
      lastTriggeredImageID: image-registry.openshift-image-registry.svc:5000/openshift/jboss-eap72-openshift@sha256:464e00edbf44d91820b9d9e95edbe6c68e075b85158f60e3d2298d94c9ec56b0
    type: ImageChange
  - type: ConfigChange
